environment: {}
parameters: {}
packages :
  - name : cloud
    actions:
      - name: app
        limits:
          timeout: 10000



    # functions :
    #   - name : index
    #     binary: false
    #     main: ''
    #     runtime: 'nodejs:default'
    #     web: true
    #     parameters: {}
    #     environment: {}
    #     annotations: {}
    #     limits: {}
